from ai_cr.diff_parser import parse_diff
from ai_cr.git_repo import locate_snippet
from ai_cr.graph.gate import compute_conclusion
from ai_cr.poller import parse_command

DIFF = """diff --git a/svc/a.go b/svc/a.go
index 1111111..2222222 100644
--- a/svc/a.go
+++ b/svc/a.go
@@ -10,6 +10,8 @@ func Run() {
 	x := 1
 	y := 2
-	z := 3
+	z := x + y
+	m[key] = z
+	go work(m)
 	return
 }
 
diff --git a/new.go b/new.go
new file mode 100644
index 0000000..3333333
--- /dev/null
+++ b/new.go
@@ -0,0 +1,2 @@
+package main
+func f() {}
"""


def test_parse_diff_line_numbers():
    files = parse_diff(DIFF)
    assert [f.path for f in files] == ["svc/a.go", "new.go"]
    a = files[0]
    assert a.added_lines() == {12, 13, 14}
    assert a.position_for(13) == {"new_line": 13}
    assert a.position_for(10) == {"new_line": 10, "old_line": 10}
    assert a.position_for(99) is None
    assert a.nearest_commentable(16) == 14
    assert "L13 +" in a.annotated() and "     - " in a.annotated()
    assert files[1].new_file and files[1].added_lines() == {1, 2}


def test_locate_snippet_ignores_whitespace_and_picks_nearest():
    content = "a\n  foo(x)\nb\nfoo(x)\nc\n"
    assert locate_snippet(content, "foo(x)", 4) == 4
    assert locate_snippet(content, "  foo(x)  \n b", 1) == 2
    assert locate_snippet(content, "bar()", 1) is None


def f(sev, status):
    return {"severity": sev, "status": status}


def test_gate():
    assert compute_conclusion([]) == "APPROVE"
    assert compute_conclusion([f("P0", "OPEN")]) == "REQUEST_CHANGES"
    assert compute_conclusion([f("P0", "ESCALATED")]) == "REQUEST_CHANGES"
    assert compute_conclusion([f("P0", "WAIVED"), f("P0", "FIXED"), f("P0", "WITHDRAWN")]) == "APPROVE"
    assert compute_conclusion([f("P1", "OPEN")]) == "REQUEST_CHANGES"
    assert compute_conclusion([f("P1", "ESCALATED")]) == "COMMENT"
    assert compute_conclusion([f("P1", "DEFERRED")]) == "APPROVE"
    assert compute_conclusion([f("P2", "OPEN")]) == "COMMENT"
    assert compute_conclusion([f("P0", "NEW")]) == "APPROVE"


def test_parse_command():
    assert parse_command("/ai-confirm 确实有竞态") == ("confirm", "确实有竞态")
    assert parse_command("/ai-downgrade P2") == ("downgrade", "P2")
    assert parse_command("/AI-review") == ("review", "")
    assert parse_command("我觉得 /ai-accept") is None


def test_clean_evidence():
    from ai_cr.git_repo import clean_evidence
    raw = 'L10 +  go func() {\\\\nL11 + \\\\tcache[k] = v\\\\nL12 + }()\\n} '
    assert [x.strip() for x in clean_evidence(raw).splitlines()] == ["go func() {", "cache[k] = v", "}()", "}"]
    assert clean_evidence("   12| x := 1\n   13| y := 2") == "x := 1\ny := 2"
    assert clean_evidence("```go\nmu.Lock()\n```") == "mu.Lock()"
    assert clean_evidence("cache[k] = v") == "cache[k] = v"


def test_locate_evidence_handles_escaped_and_fuzzy():
    from ai_cr.git_repo import locate_evidence
    content = "package svc\n\nfunc Put(k string, v int) {\n\tgo func() {\n\t\tcache[k] = v\n\t}()\n}\n"
    escaped = 'func Put(k string, v int) {\\\\n\\\\\\tgo func() {\\\\n\\\\\\t    cache[k] = v\\\\n\\\\\\t}()\\\\n}'
    assert locate_evidence(content, escaped, 3) == 3
    # 模型改写了一行，但大部分行仍能在附近找到
    assert locate_evidence(content, "go func() {\n    cache[k] = v // 写入\n}()", 4) == 4
    assert locate_evidence(content, "mu.Lock()\nother()", 4) is None


def test_lint_new_issues_ignores_line_shift():
    from ai_cr.static_analysis import LintIssue, new_issues
    base = [LintIssue("errcheck", "a.go", 10, "x not checked"), LintIssue("unused", "a.go", 30, "func old is unused")]
    head = [LintIssue("errcheck", "a.go", 14, "x not checked"),          # 历史问题，行号因改动下移
            LintIssue("unused", "a.go", 50, "func helper is unused")]     # 本次引入
    assert [i.text for i in new_issues(head, base)] == ["func helper is unused"]


def test_match_dedupes_same_title_nearby():
    from ai_cr.graph.nodes import Nodes
    a = {"fingerprint": "a", "file": "x.go", "line": 214, "category": "bug", "title": "retries 为 0 时行为未明确"}
    b = {"fingerprint": "b", "file": "x.go", "line": 217, "category": "error_handling", "title": "retries 为 0 时行为未明确"}
    c = {"fingerprint": "c", "file": "x.go", "line": 240, "category": "bug", "title": "retries 为 0 时行为未明确"}
    assert Nodes._match(b, [a]) == 0
    assert Nodes._match(c, [a]) is None


def test_is_generated():
    from ai_cr.graph.nodes import is_generated
    assert is_generated("// Code generated by MockGen. DO NOT EDIT.\n// Source: x.go\n\npackage svc\n")
    assert is_generated("// Copyright x\n\n// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n")
    assert not is_generated("package svc\n\n// Code generated elsewhere, feel free to edit.\n")
    assert not is_generated(None)


def test_v1_version_line_stripped_before_migrate():
    from ai_cr.static_analysis import V1_VERSION_RE
    assert V1_VERSION_RE.sub("", 'version: "1"\n\nrun:\n  go: "1.25"\n') == '\nrun:\n  go: "1.25"\n'
    assert V1_VERSION_RE.sub("", "version: 1 # old\nlinters: {}\n") == "linters: {}\n"
    assert V1_VERSION_RE.sub("", 'run:\n  version: "1"\n') == 'run:\n  version: "1"\n'  # 只动顶层


def test_parse_job_log_takes_latest_segment():
    from ai_cr.ui import parse_job_log
    lines = """2026-09-28 21:50:00,000 INFO ai_cr.worker: 处理任务 #7 new_push g/p!1
2026-09-28 21:50:01,000 INFO ai_cr.graph.nodes: g/p!1 发布完成，结论 APPROVE
2026-09-28 21:56:13,827 INFO ai_cr.worker: 处理任务 #11 new_push g/p!462
2026-09-28 21:56:19,143 WARNING ai_cr.static_analysis: golangci-lint 执行失败（exit 3）: boom
level=error msg="续行"
2026-09-28 21:57:18,619 INFO ai_cr.graph.nodes: g/p!462 待审 3 个文件块
2026-09-28 21:58:00,000 INFO httpx2: HTTP Request: POST http://127.0.0.1:1234/v1/chat/completions
2026-09-28 21:58:30,000 INFO ai_cr.graph.nodes:   a/b.go (1/2): 2 条候选问题
2026-09-28 21:59:00,000 INFO ai_cr.graph.nodes:   a/b.go (2/2): 0 条候选问题
2026-09-28 22:00:00,000 INFO ai_cr.worker: 处理任务 #12 dev_reply g/p!1""".splitlines()
    p = parse_job_log(lines, 11)
    assert p["phase"] == "review" and p["total"] == 3 and p["conclusion"] is None
    assert [(c["chunk"], c["n"], c["since"][11:]) for c in p["chunks"]] == [(1, 2, "21:57:18"), (2, 0, "21:58:30")]
    assert p["cursor_ts"].endswith("21:59:00")
    assert "续行" in p["warnings"][0] and not any("HTTP Request" in x for x in p["lines"])
    assert parse_job_log(lines, 7)["phase"] == "done"
    assert parse_job_log(lines, 99) == {"found": False}


def test_is_generated_detects_minified():
    from ai_cr.graph.nodes import is_generated

    assert is_generated("const _0x5b0f=_0x2898;" + "x" * 5000)
    assert not is_generated("package main\n\nfunc f() {}\n")


def test_chunks_split_oversized_hunk_and_truncate_long_lines():
    from ai_cr.diff_parser import DiffLine, FileDiff, Hunk

    lines = [DiffLine("-", 1, None, "x" * 50000), DiffLine("+", None, 1, "y" * 50000)]
    lines += [DiffLine("+", None, i, "z" * 200) for i in range(2, 600)]
    fd = FileDiff("a.js", "a.js", hunks=[Hunk("@@ -1 +1,599 @@", lines)])
    groups = fd.chunks(48000)
    assert len(groups) > 1
    assert all(len(fd.annotated(g)) <= 48000 for g in groups)
    text = "\n".join(fd.annotated(g) for g in groups)
    assert "截断，原长 50000 字符" in text and "L599 +" in text


def test_is_unavailable():
    import httpx
    import openai

    from ai_cr.llm import is_unavailable

    req = httpx.Request("POST", "http://127.0.0.1:1234/v1/chat/completions")
    assert is_unavailable(openai.APIConnectionError(request=req))
    assert not is_unavailable(openai.APITimeoutError(request=req))
    assert is_unavailable(RuntimeError("Error code: 400 - {'error': 'Model unloaded.'}"))
    assert not is_unavailable(RuntimeError("request (64879 tokens) exceeds the available context size"))


def test_drain_requeues_when_model_unavailable(monkeypatch):
    from types import SimpleNamespace

    from ai_cr import worker

    class Store:
        def __init__(self):
            self.jobs = [{"id": 1}, {"id": 2}]
            self.log = []

        def next_job(self):
            return self.jobs.pop(0) if self.jobs else None

        def requeue_job(self, job_id):
            self.log.append(("requeue", job_id))

        def finish_job(self, job_id, error=None):
            self.log.append(("finish", job_id, error))

    def run_job(deps, graph, job, resume=False):
        raise RuntimeError("Error code: 400 - {'error': 'Model unloaded.'}")

    monkeypatch.setattr(worker, "run_job", run_job)
    store = Store()
    worker.drain(SimpleNamespace(store=store), graph=None)
    # 放回队列并停止消费，等模型就绪；不能把后面的任务也一个个标记失败
    assert store.log == [("requeue", 1)]
    assert store.jobs == [{"id": 2}]


def test_path_affinity_prefers_same_file_then_dir():
    from ai_cr.graph.nodes import _path_affinity

    target = "app/edge/internal/events/service.go"
    paths = ["pkg/x.go", "app/edge/internal/handlers/a.go", "app/edge/internal/events/types.go", target]
    assert sorted(paths, key=lambda p: _path_affinity(p, target), reverse=True) == list(reversed(paths))


def test_trace_records_call_with_step(tmp_path):
    from uuid import uuid4

    from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
    from langchain_core.outputs import ChatGeneration, LLMResult

    from ai_cr.trace import TraceHandler, TraceReader, TraceStore, step

    h = TraceHandler(TraceStore(tmp_path / "t.db"))
    run = uuid4()
    with step("审查 a.go [correctness]"):
        h.on_chat_model_start({}, [[SystemMessage("sys"), HumanMessage("看看这段 diff")]], run_id=run,
                              metadata={"thread_id": "job-7", "langgraph_node": "review_file"},
                              invocation_params={"model": "m", "temperature": 0.2})
    h.on_llm_end(LLMResult(generations=[[ChatGeneration(message=AIMessage("确认的问题：无"))]],
                           llm_output={"token_usage": {"prompt_tokens": 12, "completion_tokens": 5}}), run_id=run)
    fail = uuid4()
    h.on_chat_model_start({}, [[HumanMessage("x")]], run_id=fail, metadata={"thread_id": "job-7"})
    h.on_llm_error(RuntimeError("boom"), run_id=fail)

    r = TraceReader(tmp_path / "t.db")
    calls = r.calls("job-7")
    assert [(c["step"], c["node"], c["prompt_tokens"], c["error"]) for c in calls] == [
        ("审查 a.go [correctness]", "review_file", 12, None), ("", None, None, "boom")]
    full = r.call(calls[0]["id"])
    assert [m["role"] for m in full["request"]["messages"]] == ["system", "human"]
    assert full["response"]["content"] == "确认的问题：无"
    assert r.calls("job-8") == [] and TraceReader(tmp_path / "missing.db").calls("job-7") == []


def test_parse_job_log_resumed_job():
    from ai_cr.ui import parse_job_log

    lines = [
        "2026-09-30 15:12:36,566 INFO ai_cr.worker: 处理任务 #13 new_push g/edgenode!9",
        "2026-09-30 15:12:36,569 INFO ai_cr.worker: 从 checkpoint 恢复任务 #13",
        "2026-09-30 15:14:36,879 INFO ai_cr.graph.nodes:   cmd/main.go (1/1): 4 条候选问题",
    ]
    p = parse_job_log(lines, 13)
    assert p["resumed"] and p["chunks"][0]["since"] == "2026-09-30 15:12:36"
